server:
  port: 9090

spring:
  application:
    name: msvc-courses

  #este config sirve para evitar que tire error con el config server que no esta aun configurado
  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/coursesDB
    username: postgres
    password: 1234

  # JPA specific configs
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

